### ISSUE TITLE
Get-FalconDetections sort not working

### ISSUE THREAD

**Issue by Factorization** [CrowdStrike/psfalcon#2] opened 2021-01-19 18:18 UTC
It looks like the sort parameter validation set is not correct for the Get-FalconDetection cmdlet.

Here is a screenshot:
![image](https://user-images.githubusercontent.com/10674846/105075544-bcfb7380-5a3e-11eb-966f-18176c569ff4.png)

**Comment by bk-cs** [comment] 2021-01-19 19:24
Thanks!

It seems like Get-FalconDetection is pulling the sort criteria from "Get-FalconIOARule". Is it possible you ran a "Get-FalconIOARule -Help" before you ran "Get-FalconDetection -Help"?

I'm looking into this now...

**Comment by Factorization** [comment] 2021-01-19 19:28
No I didn't run Get-FalconOARule -Help. I did run Get-FalconFirewallPolicy -Ids <ID> before I ran the Get-FalconDetection. Could it be pulling the sort criteria from that function?

**Comment by bk-cs** [comment] 2021-01-19 19:49
Yes, I can reproduce this pretty easily. For some reason it's keeping "Sort" criteria from other functions when they've been looked up. "Get-FalconFirewallRule" matches the -Sort criteria in your screenshot. 

You can see this bug in action if you run these commands in order:
Get-FalconDetection -Help <-- normal
Get-FalconFirewallRule -Help
Get-FalconDetection -Help <-- broken

**Comment by bk-cs** [comment] 2021-01-19 20:53
It looks like it's not just 'sort', it's keeping parameter properties too, like 'limit'. Thanks for finding this--it didn't happen in my testing, likely because I didn't switch back and forth between commands while I tested.

It'll take me a bit to figure it out...

**Comment by bk-cs** [comment] 2021-01-20 01:27
I made some changes to reduce the size and complexity of the involved functions, but haven't figured out why the data is being re-used yet. I'll keep working on it and update as soon as I've figured it out.

**Comment by Factorization** [comment] 2021-01-20 02:53
Thanks for the update. It looks like this commit made some changes to the parameters for some of the commands. I am now seeing errors with the command Get-FalconHost -Detailed -All. It looks like the loop from the -All uses -Ids, but -Ids is no longer a valid parameter. I think it should be -Id. You might be able to add an alias to the -Id parameter for backwards compatibility. Did all of the commands that used -Ids, get switched to the singular version -Id?

![image](https://user-images.githubusercontent.com/10674846/105120347-f1931d80-5a86-11eb-86d9-b278493a0b03.png)

**Comment by bk-cs** [comment] 2021-01-20 03:49
It reads it directly from the API field, so whatever the API field is using, it's using. Figuring out how to stop the 'sharing' of parameters made the secondary API disappear ('/detects/entities/detects/v1' in this case). I'm looking at that now. :)

**Comment by bk-cs** [comment] 2021-01-20 03:54
I can't reproduce this one--can you reinstall your module?

**Comment by Factorization** [comment] 2021-01-20 04:18
That fixed the issue. It's weird, I just did a git pull to update previously. This time I deleted and re-cloned the repo. I still feel like some of the parameters are changing. For example, when I run Find-FalconDuplicate, there is no -Hosts parameter anymore. I also think the Invoke-FalconHostAction use to take a -ActionName parameter, but now the parameter is called -Name.

**Comment by bk-cs** [comment] 2021-01-20 04:22
-ActionName was renamed to -Name earlier today, and Find-FalconDuplicate still has -Hosts. I've seen issues when a module is not fully removed and reinstalled when you're copying files in, so I'm thinking that might be it...

I'm still troubleshooting the "sharing" of parameters because I'm still seeing it happen. I think I'm most of the way there.

**Comment by Factorization** [comment] 2021-01-20 04:24
Find-FalconDuplicate shows no -Hosts parameter for me:
![image](https://user-images.githubusercontent.com/10674846/105126803-5dc84e00-5a94-11eb-9f25-1440f6ed7bb9.png)

**Comment by bk-cs** [comment] 2021-01-20 04:39
Ok, I'll see if I can reproduce that. I'm might have to pick it back up in the morning.

**Comment by Factorization** [comment] 2021-01-20 04:53
No worries. Thanks for the help!

**Comment by bk-cs** [comment] 2021-01-20 04:53
I was able to reproduce it. I love whack-a-mole!

**Comment by bk-cs** [comment] 2021-01-20 06:38
Ok, I think it's all sorted out now.

I completely re-wrote how the "parameters" are grabbed for each command. I tested by alternating between different commands (i.e. Get-FalconDetection > Get-FalconIOARule > Get-FalconFirewallPolicy > Get-FalconDetection) and was unable to get them to "re-use" properties like they were before.

I also verified that Find-FalconDuplicate shows Hosts, which was broken as part of the original changes in my first attempt.

I expect that these changes will fix all the issues you've mentioned, so I'm going to close this issue. Please delete/re-install your module and reload your PowerShell session and then let me know if you still have problems.

Thanks for all your help!

**Comment by bk-cs** [comment] 2021-01-20 06:51
Ok, I think it's all sorted out now.

I completely re-wrote how the "parameters" are grabbed for each command. I tested by alternating between different commands (i.e. Get-FalconDetection > Get-FalconIOARule > Get-FalconFirewallPolicy > Get-FalconDetection) and was unable to get them to "re-use" properties like they were before.

I also verified that Find-FalconDuplicate shows Hosts, which was broken as part of the original changes in my first attempt.

I expect that these changes will fix all the issues you've mentioned, so I'm going to close this issue. Please delete/re-install your module and reload your PowerShell session and then let me know if you still have problems.

Thanks for all your help!

**Closed by bk-cs** 2021-01-20 06:51 UTC
Labels: bug

**Comment by Factorization** [comment] 2021-01-20 17:14
It looks like these updates broke Start-FalconSession. This was working before I pulled down the latest commit. Let me know if you want me to open a new issue for this error.

Here is the error I get:

![image](https://user-images.githubusercontent.com/10674846/105210243-abc66b80-5aff-11eb-8a49-392d0dbfa83a.png)

**Comment by bk-cs** [comment] 2021-01-20 18:36
Thanks for the report. I opened up a new issue to track it: https://github.com/CrowdStrike/psfalcon/issues/4
