### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by antmar904** [CrowdStrike/psfalcon#151] opened 2021-12-07 14:24 UTC
**Description of your question**
When using PSFalcon looking at host records all policies, device_policies, groups, etc list the IDs.  Seeing the name's instead would be easier so I won't have to look up the name after I retireive the ID.

**To Reproduce**
Get-FalconHost "hostname:'computername'" -Detailed -All

When looking at the host's groups all IDs are shown but I don't know what the IDs point to and seeing the name would be better.

**Expected behavior**
Get-FalconHost "hostname:'computername'" -Detailed -All

When looking at the host's groups all IDs are shown but I don't know what the IDs point to and seeing the name would be better.

**Environment (please complete the following information):**
 - OS: Windows 10
 - PowerShell: 7.2.0
 - PSFalcon: 2.1.5

**Comment by bk-cs** [comment] 2021-12-07 17:08
Identifier values are how entities are tracked within Falcon. A host is assigned to a host group by id, a host group is assigned to a policy by id--that's the only important property that needs to be there in order for the assignment to work.

PSFalcon, in general, provides the user with the data that comes directly from the Falcon APIs. When using `Get-FalconHost` (which I assume is the command you meant in your example), the `groups` property only shows ids. `device_policies` shows ids, names, timestamps, etc. The names aren't included because the names aren't there.

Here's an example of how you could append host group information to your list of hosts without having to correlate it yourself:

```
$Hosts = Get-FalconHost -Detailed -All
$Groups = Get-FalconHostGroup -Ids ($Hosts.groups | Group-Object).Name
foreach ($Item in $Hosts) {
    $Object = foreach ($Group in $Item.groups) {
        $Groups | Where-Object { $_.id -eq $Group }
    }
    $Item.groups = $Object
}
```

Once that's done, instead of a list of host group ids under `groups` for each host, you'll have the full host group information.  Alternatively, you can add `Select-Object` after `Where-Object` to choose specific properties:

```
$Hosts = Get-FalconHost -Detailed -All
$Groups = Get-FalconHostGroup -Ids ($Hosts.groups | Group-Object).Name
foreach ($Item in $Hosts) {
    $Object = foreach ($Group in $Item.groups) {
        $Groups | Where-Object { $_.id -eq $Group } | Select-Object id, name
    }
    $Item.groups = $Object
}
```

I've introduced a parameter called `-Include` where there's a clear opportunity to add useful data to a command result. `Get-FalconHost` can include `login_history`, `network_history` and `zero_trust_assessment`. It does this by sending the host ids to another API, and adds the data to the host results before returning them to the user -- the same thing that's happening in the example above. Is this the sort of thing you're asking for?

**Comment by bk-cs** [comment] 2021-12-10 16:41
I've added `group_names` as an option in the `-Include` parameter for `Get-FalconHost` for v2.1.7.

If you'd like to try it out, please replace `Public\devices.ps1` in your local module with the contents of this file: https://raw.githubusercontent.com/CrowdStrike/psfalcon/master/Public/devices.ps1

**Comment by antmar904** [comment] 2021-12-15 15:49
Instead of using the parameter "-Include" with the different options "group_names,login_history,network_history,etc" to get the addtional info for a host, can't you just include it when using "-Detailed"?

When querying a host's information, it would be nice to return the host record with all available data by using "Get-FalconHost $Filter -Detailed"

I'm just thinking of ways to make PSFalcon easier for me as I'm not efficient in PS :)

**Comment by bk-cs** [comment] 2021-12-15 16:07
Although it's technically possible, `-Detailed` was designed for a very specific purpose -- pass the ids from a `/queries/` endpoint to its associated `/entities/` endpoint. 

Appending the group names involves an additional set of work (even though it involves similar steps), because it requires that a `/devices/` API result also includes data from a `/host-group/` API result. Although I've had several people ask for a similar request of adding group names, it's not enough of the PSFalcon user population that it makes sense to increase the amount of work required to output `Get-FalconHost -Detailed` information.

To get the results for 5,000 devices, `-Detailed` involves:

1 call to `GET /devices/queries/devices-scroll/v1` 
10 calls to `GET /devices/entities/devices/v1`

`-Include login_history` adds:

10 calls to `POST /devices/combined/devices/login_history/v1`

`-Include network_history` adds:

10 calls to `POST /devices/combined/devices/login_history/v1`

`-Include zero_trust_assessment` adds:

10 calls to `GET /zero-trust-assessment/entities/audit/v1`

`-Include group_names` adds:

1 or more calls (depending on the amount of groups) to `GET /host-group/combined/host-groups/v1`

Out of all the `-Include` options, `group_names` is probably the smallest amount of work. But given that it also requires additional permissions (`host-group:read` rather than just `devices:read`) it's kind of a "square peg, round hole" situation. 

To me, it feels easier to add it as an `-Include` option, as it's a clear delineation that it's pulling data from somewhere else, to manipulate the final output.

**Comment by antmar904** [comment] 2021-12-15 16:25
Great, thank you for the detailed information!  One last question.  When adding "-Include zero_trust_assessment" I'm not seeing the output for it...  Under what property should I see it?  Thanks again.

**Comment by bk-cs** [comment] 2021-12-15 20:09
It should be attached to the `zero_trust_assessment` property that is created. However, you asking that question prompted me to realize that there is a [typo in v2.1.6 that prevents this from happening](https://github.com/CrowdStrike/psfalcon/issues/158). There are instructions included in that issue that will fix the problem for you before the next release.

**Comment by bk-cs** [comment] 2022-01-28 01:20
Closing due to [v2.1.7 release](https://github.com/CrowdStrike/psfalcon/releases/tag/2.1.7).

**Closed by bk-cs** 2022-01-28 01:20 UTC
Labels: question
