### ISSUE TITLE
Possible to check OAuth2 Token status?

### ISSUE THREAD

**Issue by datorr2** [CrowdStrike/psfalcon#34] opened 2021-03-18 00:40 UTC
I would like to be able to write scripts that utilize the PSFalcon module for our active responders/admins.  In the scripts, I would like to check to see if there's an OAuth2 token already present in the session; if not, request that the user enter one (or pull from an external source, such as an environmental variable, or dot-sourcing a script file).

The only commands I see that involve tokens are the `Request-FalconToken` and `Revoke-FalconToken`.  I've tried to see if Request-FalconToken returns an error or not, but it doesn't look like it returns anything.

Is there a way to check if a token was already requested prior to running `Request-FalconToken` ?

**Comment by bk-cs** [comment] 2021-03-18 15:18
No, the token is generally not exposed to the user.

If any command is run and a token has not already been requested, the user will be prompted to enter in their Client ID and Secret to request one. Would that solve your problem, or would you need to have the token status exposed somehow?

**Comment by datorr2** [comment] 2021-03-18 23:08
The token itself wouldn't need to be exposed, but maybe a way to check if one is made and current, even if a boolean?

Maybe even something as simple as `Test-FalconToken` returns `$True` if there's a valid token, or `$False` if it is invalid or expired?

**Comment by bk-cs** [comment] 2021-03-19 19:55
Yeah, that's a pretty simple request. I've got a function called `Show-FalconModule` that gives some diagnostic information about the module. I could add in some additional fields like "Current Client ID", "Active Token Retrieved", etc. or create the `Test-FalconToken` command that's dedicated to the token itself.

Would any other information be valuable? The cloud/API hostname being used, the client id that the token was request with, etc.?

**Comment by datorr2** [comment] 2021-03-19 20:43
Client ID and Cloud/API hostname could be useful to distinguish between different endpoints, or verifying which API key is in use.

**Comment by bk-cs** [comment] 2021-03-19 22:47
I've added `Test-FalconToken` to the next version of PSFalcon which is currently in development (v2.0.7). It will display the cached `ClientId`, `Hostname` and `MemberCid` (as provided to `Request-FalconToken`) along with a true/false value if there is currently an access token and it is due to expire in more than 30 seconds (which is the same check performed as you run commands--the token is refreshed if it's due to expire within the next 30 seconds).

I'll close this issue as soon as the changes have been committed.

**Comment by finackninja** [comment] 2021-04-12 22:22
I see that a solution for this is planned for the next revision. 🙌 Because the current implementation makes it very difficult to ensure that things were handled correctly with other code.

In 2.0 - 2.0.6, not only can you not check with non-PsFalcon code to see if an access token has been granted, but you can't even catch an exception for `Request-FalconToken` because it doesn't throw one when there is a failure.

You can see evidence of this below. An exception is _not_ thrown even though I specified `-ErrorAction Stop`; however, an error did in fact occur as you can see in the second run of the command without the `try {} catch {}` block.

```
try {
>>     Request-FalconToken -ClientId 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX' -ClientSecret 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX' -ErrorAction Stop
>>     Write-Host "`n ********* Exception NOT thrown **********`n"
>> }
>> catch {
>>     Write-Host "`n ********* Exception thrown **********`n"
>> }
>>
>> Request-FalconToken -ClientId 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX' -ClientSecret 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'

 ********* Exception NOT thrown **********

Format-Result: C:\Program Files\WindowsPowerShell\Modules\PsFalcon\2.0.6\Private\Private.ps1:995
Line |
 995 |                  Format-Result -Response $Response -Endpoint $Endpoint
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | 403: Failed to issue access token - Not Authorized
```

In addition to `Test-FalconToken`, it would be nice if functions returned catchable exceptions.

**Comment by bk-cs** [comment] 2021-04-13 00:35
I'm guessing that the error is not catchable because it's not `Request-FalconToken` that's doing the work--all PSFalcon commands essentially just gather input, then pass that input to other functions to send it to the API--so presumably any error would be coming from `Invoke-Request` or one of it's helper functions (which is why you see `Format-Result`).

Are you able to replicate this with other functions, or is it only `Request-FalconToken`? Admittedly I am not great with error handling, so I appreciate feedback on places where you're finding this.

**Comment by finackninja** [comment] 2021-04-13 14:18
> I'm guessing that the error is not catchable because it's not `Request-FalconToken` that's doing the work--all PSFalcon commands essentially just gather input, then pass that input to other functions to send it to the API--so presumably any error would be coming from `Invoke-Request` or one of it's helper functions (which is why you see `Format-Result`).

That makes sense. I think you would have to add a `throw` in `Request-FalconToken` in order for it itself to return an exception if it experiences an error getting an access token from one of the other functions it depends on.

The trouble now is caused by the following things all being true:
- The cmdlet doesn't return anything regardless of whether it succeeds or fails.
- It doesn't throw an exception if it fails.
- There is no way for other code working with PsFalcon 2.0 to verify if an access token has been issued.

In PsFalcon 1.x, you could check `$Falcon.token` or what was returned by the `Get-CsToken` cmdlet. But in PsFalcon 2.0, currently there is just no way for other code to know if `Request-FalconToken` worked or not.

> Are you able to replicate this with other functions, or is it only `Request-FalconToken`? Admittedly I am not great with error handling, so I appreciate feedback on places where you're finding this.

I haven't really needed to try to catch exceptions for any of the other PsFalcon cmdlets yet, so I can't say for sure where else the problem might exist. I've only noticed it so far on `Request-FalconToken`.

**Comment by bk-cs** [comment] 2021-04-13 16:25
Thank you for the feedback! I'll see what I can figure out.

If you weren't aware, you can also use the `-Verbose` and `-Debug` flags to get some additional output, which (at least visually) would give you confirmation that the access token request was successful.

**Comment by bk-cs** [comment] 2021-04-13 18:21
Ok, I've added a couple things... the internal functions use try/catch loops that output exceptions (rather than just outputting the error) and I added a check before submitting a request to validate the URL. From my testing, this seems to properly work, but I'm not sure whether or not `-ErrorAction Stop` is going to function completely as expected.

These will be part of the v2.0.7 release which will be out ASAP (hoping the end of this week).

**Closed** 2021-04-15 20:57 UTC
Labels: bug, enhancement
